version: '2'

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.50.0.0/16
          gateway: 10.50.0.1
services:
  bootnode:
    container_name: bootnode
    image: syneblock/quorum
    environment:
      - BOOTNODE_IP=bootnode
    working_dir: /bootnode
    command: ["bash" , "start_bootnode.sh"]
    volumes:
      - ./bootnode:/bootnode        
    networks:
      vpcbr:
        ipv4_address: 10.50.0.2
  node1:
    container_name: node1
    image: syneblock/quorum
    environment:
      - CORE_node1_NETWORKID=node1
      - CORE_NODE_IP=node1
      - CORE_MASTERNODE_IP=node1 
      - CORE_BOOTNODE=bootnode
      - CORE_BOOTNODE_LISTENPORT=33445
    working_dir: /node1
    command: ["bash" , "start_node.sh"]
    links: 
      - bootnode:bootnode
    volumes:
      - ./node1:/node1
    ports:
      - 22000:22000
    depends_on:
      - bootnode
    networks:
      vpcbr:
        ipv4_address: 10.50.0.4
  node2:
    container_name: node2
    image: syneblock/quorum
    environment:
      - CORE_node2_NETWORKID=node2
      - CORE_NODE_IP=node2
      - CORE_MASTERNODE_IP=node1 
      - CORE_BOOTNODE=bootnode
      - CORE_BOOTNODE_LISTENPORT=33445
    working_dir: /node2
    command: ["bash" , "start_node.sh"]
    links: 
      - bootnode:bootnode
    volumes:
      - ./node2:/node2
    ports:
      - 22001:22000
    depends_on:
      - bootnode
    networks:
      vpcbr:
        ipv4_address: 10.50.0.5
